parameters:
- name: artifact_path
  displayName: artifact path
  type: string
  default: 'test_path'

trigger:
- master
- releases/*

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    # Python37:
    #   python.version: '3.7'
    Python39:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

# - script: |
#     python -m pip install --upgrade pip
#     pip install -r requirements.txt
#   displayName: 'Install dependencies'

# - script: |
#     pip install pytest pytest-azurepipelines
#     pytest
#   displayName: 'pytest'

# - script: echo 'artifact_path=${{ parameters.artifact_path }}'
#   condition: eq('${{ parameters.artifact_path }}', 'test_path')
#   displayName: 'parameter usage'

# - script: python startup.py
#   displayName: 'Run startup.py'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(Build.Repository.LocalPath)/sample/hello_sample.py'
    arguments: '--world Venus'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)' # string. Required. Root folder or file to archive. Default: $(Build.BinariesDirectory).
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true